Importing Libraries

In [29]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score,classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

Loading the dataset

In [30]:
iris_data = pd.read_csv('/content/iris_data.csv',header=None)
x=iris_data.drop([4],axis=1)
y=iris_data[4]

In [31]:
print(x)
print(y)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]
0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: 4, Length: 150, dtype: object


Splitting dataset

In [32]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,stratify=y,random_state=1)

In [33]:
print(x_train)
print(x_test)
print(y_train)
print(y_test)

       0    1    2    3
137  6.4  3.1  5.5  1.8
21   5.1  3.7  1.5  0.4
133  6.3  2.8  5.1  1.5
135  7.7  3.0  6.1  2.3
74   6.4  2.9  4.3  1.3
..   ...  ...  ...  ...
134  6.1  2.6  5.6  1.4
43   5.0  3.5  1.6  0.6
95   5.7  3.0  4.2  1.2
37   4.9  3.1  1.5  0.1
64   5.6  2.9  3.6  1.3

[112 rows x 4 columns]
       0    1    2    3
113  5.7  2.5  5.0  2.0
7    5.0  3.4  1.5  0.2
0    5.1  3.5  1.4  0.2
11   4.8  3.4  1.6  0.2
93   5.0  2.3  3.3  1.0
49   5.0  3.3  1.4  0.2
99   5.7  2.8  4.1  1.3
106  4.9  2.5  4.5  1.7
12   4.8  3.0  1.4  0.1
91   6.1  3.0  4.6  1.4
107  7.3  2.9  6.3  1.8
127  6.1  3.0  4.9  1.8
121  5.6  2.8  4.9  2.0
54   6.5  2.8  4.6  1.5
112  6.8  3.0  5.5  2.1
76   6.8  2.8  4.8  1.4
145  6.7  3.0  5.2  2.3
73   6.1  2.8  4.7  1.2
68   6.2  2.2  4.5  1.5
66   5.6  3.0  4.5  1.5
50   7.0  3.2  4.7  1.4
108  6.7  2.5  5.8  1.8
142  5.8  2.7  5.1  1.9
84   5.4  3.0  4.5  1.5
8    4.4  2.9  1.4  0.2
9    4.9  3.1  1.5  0.1
15   5.7  4.4  1.5  0.4
62   6.0  2.2  4

Removing the mean and scaling to unit variance using StandardScaler

In [34]:
scaler=StandardScaler()
x_train_scaled=scaler.fit_transform(x_train)
x_test_scaled=scaler.fit_transform(x_test)
print(x_test_scaled)

[[-0.14620354 -1.14642475  0.73816126  1.09768515]
 [-1.05062545  0.87459208 -1.3731387  -1.3967223 ]
 [-0.92142232  1.0991495  -1.43346155 -1.3967223 ]
 [-1.30903171  0.87459208 -1.31281584 -1.3967223 ]
 [-1.05062545 -1.5955396  -0.28732729 -0.28809677]
 [-1.05062545  0.65003465 -1.43346155 -1.3967223 ]
 [-0.14620354 -0.47275247  0.19525556  0.12763781]
 [-1.17982858 -1.14642475  0.43654698  0.68195058]
 [-1.30903171 -0.02363762 -1.43346155 -1.53530049]
 [ 0.37060898 -0.02363762  0.49686984  0.266216  ]
 [ 1.92104653 -0.24819505  1.52235839  0.82052877]
 [ 0.37060898 -0.02363762  0.67783841  0.82052877]
 [-0.27540667 -0.47275247  0.67783841  1.09768515]
 [ 0.88742149 -0.47275247  0.49686984  0.40479419]
 [ 1.27503088 -0.02363762  1.03977554  1.23626334]
 [ 1.27503088 -0.47275247  0.61751555  0.266216  ]
 [ 1.14582775 -0.02363762  0.85880698  1.51341973]
 [ 0.37060898 -0.47275247  0.5571927  -0.01094038]
 [ 0.49981211 -1.82009702  0.43654698  0.40479419]
 [-0.27540667 -0.02363762  0.43

Applying PCA for dimensionality reduction

In [35]:
pca = PCA(n_components=2)
x_train_pca = pca.fit_transform(x_train_scaled)
x_test_pca = pca.fit_transform(x_test_scaled)

In [36]:
#This is an attribute of the PCA object in scikit-learn. It's a NumPy array where each element represents the percentage of the variance in the original data that is explained by each corresponding principal component
print("Explained variance ratio by PCA components:", pca.explained_variance_ratio_)

Explained variance ratio by PCA components: [0.73338646 0.20502892]


In [37]:
svm_model=SVC(kernel='linear',C=1.0,gamma=0.1,random_state=42)
svm_model.fit(x_train_pca,y_train)
y_pred_svm=svm_model.predict(x_test_pca)

In [38]:
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(x_train_pca,y_train)
y_pred_knn = knn_model.predict(x_test_pca)

In [39]:
acc_svm=accuracy_score(y_test,y_pred_svm)
acc_knn=accuracy_score(y_test,y_pred_knn)

In [40]:

print("\nComparison:")
print(f"SVM Accuracy: {acc_svm*100:.2f}%")
print(f"KNN Accuracy: {acc_knn*100:.2f}%")


Comparison:
SVM Accuracy: 84.21%
KNN Accuracy: 81.58%
